# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='model_1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
